# Generated by Django 5.1.5 on 2025-04-21 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='brand_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='car_models/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='mods.carbrand')),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('before_image', models.ImageField(upload_to='modifications/before/')),
                ('after_image', models.ImageField(upload_to='modifications/after/')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='mods.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ModificationShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('location_url', models.URLField()),
                ('phone', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('services', models.ManyToManyField(related_name='shops', to='mods.modification')),
            ],
        ),
    ]
